import { Testimonial } from "@/types";

export const TESTIMONIALS: Testimonial[] = [
  {
    name: "Priya Ramachandran",
    avatar: "PR",
    avatarBg: "linear-gradient(135deg, #FF6B6B, #FF8E53)",
    year: "2025",
    text: "I was stuck at Band 6 in IELTS Writing for months. This session completely changed how I approach Task 2. The structure, idea planning, and examiner-focused tips helped me improve to Band 7.5 in my next attempt.",
    highlight: "Band 6 → 7.5 in Writing",
    rating: 5,
    course: "IELTS Writing (Task 1 & 2)",
  },
  {
    name: "Arjun Krishnamurthy",
    avatar: "AK",
    avatarBg: "linear-gradient(135deg, #667EEA, #764BA2)",
    year: "2024",
    text: "I always lost marks in Task 1 because I didn’t understand what examiners expect. The training simplified charts, maps, and reports clearly. My Task 1 performance improved significantly.",
    highlight: "Task 1 structure mastered",
    rating: 5,
    course: "IELTS Academic Writing",
  },
  {
    name: "Sneha Murugan",
    avatar: "SM",
    avatarBg: "linear-gradient(135deg, #11998E, #38EF7D)",
    year: "2025",
    text: "Understanding common mistakes that reduce band scores was the biggest takeaway. The live corrections showed me exactly why I was stuck at Band 6. I finally crossed Band 7 in Writing.",
    highlight: "Avoided examiner penalties",
    rating: 5,
    course: "IELTS Writing Strategy",
  },
  {
    name: "Rahul Venkatesh",
    avatar: "RV",
    avatarBg: "linear-gradient(135deg, #F093FB, #F5576C)",
    year: "2024",
    text: "I used to think writing longer essays meant higher marks. This training taught me clarity, coherence, and answering the question directly. It completely changed my Task 2 approach.",
    highlight: "Clear Task 2 approach",
    rating: 5,
    course: "IELTS Writing Task 2",
  },
  {
    name: "Harini",
    avatar: "HR",
    avatarBg: "linear-gradient(135deg, #4FACFE, #00F2FE)",
    year: "2025",
    text: "The planning techniques saved me a lot of time during the exam. I learned how to structure essays quickly and write confidently without panic.",
    highlight: "Faster planning & better flow",
    rating: 5,
    course: "IELTS Writing Time Management",
  },
  {
    name: "Karthik Sundaram",
    avatar: "KS",
    avatarBg: "linear-gradient(135deg, #FA709A, #FEE140)",
    year: "2024",
    text: "I struggled with IELTS Writing in two attempts before this training. The feedback examples and band descriptors finally made sense. I cleared my required Writing band in the very next attempt.",
    highlight: "Cleared Writing band requirement",
    rating: 5,
    course: "IELTS Writing Band Improvement",
  },
];
