import { Testimonial } from "@/types";

export const TESTIMONIALS: Testimonial[] = [
  {
    name: "Priya Ramachandran",
    avatar: "PR",
    avatarBg: "linear-gradient(135deg, #FF6B6B, #FF8E53)",
    year: "2025",
    text: "I was stuck at Band 6 in IELTS Writing for months. This webinar completely changed how I approach Task 2. The structure, idea planning, and examiner-focused tips helped me jump to Band 7.5 in my next attempt.",
    highlight: "Band 6 → 7.5 in Writing",
    rating: 5,
    course: "IELTS Writing (Task 1 & 2)",
  },
  {
    name: "Arjun Krishnamurthy",
    avatar: "AK",
    avatarBg: "linear-gradient(135deg, #667EEA, #764BA2)",
    year: "2024",
    text: "I always lost marks in Task 1 because I didn’t know what examiners actually look for. The webinar broke down charts, maps, and reports in a very simple way. My Task 1 score improved immediately.",
    highlight: "Task 1 structure mastered",
    rating: 5,
    course: "IELTS Academic Writing",
  },
  {
    name: "Sneha Murugan",
    avatar: "SM",
    avatarBg: "linear-gradient(135deg, #11998E, #38EF7D)",
    year: "2025",
    text: "What helped me most was understanding common mistakes that reduce bands. The live examples and corrections showed me exactly why I was stuck at Band 6. I finally crossed Band 7 in Writing.",
    highlight: "Avoided examiner penalties",
    rating: 5,
    course: "IELTS Writing Strategy",
  },
  {
    name: "Rahul Venkatesh",
    avatar: "RV",
    avatarBg: "linear-gradient(135deg, #F093FB, #F5576C)",
    year: "2024",
    text: "I used to write long essays thinking more words meant higher marks. This session taught me clarity, coherence, and how to directly answer the question. Huge mindset shift for Task 2.",
    highlight: "Clear Task 2 approach",
    rating: 5,
    course: "IELTS Writing Task 2",
  },
  {
    name: "Divya Lakshmi",
    avatar: "DL",
    avatarBg: "linear-gradient(135deg, #4FACFE, #00F2FE)",
    year: "2025",
    text: "The planning techniques shared in the webinar saved me so much time during the exam. I learned how to structure essays in 5 minutes and write confidently without panic.",
    highlight: "Faster planning & better flow",
    rating: 5,
    course: "IELTS Writing Time Management",
  },
  {
    name: "Karthik Sundaram",
    avatar: "KS",
    avatarBg: "linear-gradient(135deg, #FA709A, #FEE140)",
    year: "2024",
    text: "I failed IELTS Writing twice before attending this session. The feedback examples and band descriptors finally made sense. I cleared my required Writing band in the very next attempt.",
    highlight: "Cleared Writing band requirement",
    rating: 5,
    course: "IELTS Writing Band Improvement",
  },
];
